language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.11"
matrix:
  allow_failures:
    - node_js: "0.11"
  fast_finish: true  
before_install:
  - sudo echo "deb http://debian.gamers-coin.org:8080 debian/" >> /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get install gamerscoind
after_install:
  - git submodule update --init
